SampleFacebookApp/Controllers/WagerBoardController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Mvc.Facebook;
using Microsoft.AspNet.Mvc.Facebook.Client;
using SampleFacebookApp.Models;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Generic;
using System.ServiceModel;
using System.Text.RegularExpressions;

namespace SampleFacebookApp.Controllers
{
     [Serializable]
    public class WagerBoardController : Controller
    {

         /*user profile*/

         public JsonResult myprofile()
         {
             var conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["ptpcon"].ConnectionString);
             conn.Open();

             PtpBettingDetial bet = new PtpBettingDetial();

             string queryString = "SELECT Total_chip_count,highest_chip_win,number_of_wagers,number_of_tournaments,no_of_wins,total_coin_count,current_level,no_of_ex_wins FROM dbo.PTP_Facebook_Player where Facebook_id =" + Session["fbid"];
             SqlCommand command = new SqlCommand(queryString, conn);
             SqlDataReader sdr = command.ExecuteReader();
             if (sdr.Read())
             {
                 bet.chipbalance = sdr.GetValue(0).ToString();
                 bet.high_won = sdr.GetValue(1).ToString();
                 bet.hands_played = sdr.GetValue(2).ToString();
                 bet.tournament_played = sdr.GetValue(3).ToString();
                 bet.tournament_win = sdr.GetValue(4).ToString();
                 bet.coinbalance = sdr.GetValue(5).ToString();
                 bet.cur_level = "1";

                 //game level condition
                 if (sdr.GetValue(6).ToString() == "1")
                 {
                     if (sdr.GetValue(4).ToString() == "5")
                     {
                         bet.cur_level = "2";
                         if (sdr.GetValue(7).ToString() == "10")
                         {
                             bet.cur_level = "3";

                             if (Session["winhands"].ToString() == "4")
                             {
                                 bet.cur_level = "4";

                                 if (Session["winhands"].ToString() == "6")
                                 {
                                     bet.cur_level = "5";

                                     if ((sdr.GetValue(4).ToString() == "5") && (sdr.GetValue(0).ToString() == "20000"))
                                     {
                                         bet.cur_level = "6";
                                     } //level 6 close

                                 } //level 5 close
                             } //level 4 close
                         } //level 3 close
                     } //level 2 close
                 } //level 1 close
                 conn.Close();




             } //action close

            // String value = "chipbal:bet.chipbalance + "coin:" + bet.coinbalance + "cur_level:" + bet.cur_level;

             String value = bet.chipbalance;
             return Json(new { chipbal = bet.chipbalance, coinbal = bet.coinbalance }, JsonRequestBehavior.AllowGet);
            
         }
         
         /*user Your Score*/

         public ActionResult ScoreBoard()
         {
             var conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["ptpcon"].ConnectionString);
             conn.Open();

             PtpBettingDetial bet = new PtpBettingDetial();

             string queryString = "SELECT Total_chip_count,highest_chip_win,number_of_wagers,number_of_tournaments,no_of_wins,total_coin_count,current_level,no_of_ex_wins,Total_tmt_won FROM dbo.PTP_Facebook_Player where Facebook_id =" + Session["fbid"];
             SqlCommand command = new SqlCommand(queryString, conn);
             SqlDataReader sdr = command.ExecuteReader();
             if (sdr.Read())
             {
                 bet.chipbalance = sdr.GetValue(0).ToString();
                 bet.high_won = sdr.GetValue(1).ToString();
                 bet.hands_played = sdr.GetValue(2).ToString();
                 bet.tournament_played = sdr.GetValue(3).ToString();
                 bet.tournament_win = sdr.GetValue(8).ToString();
                 bet.coinbalance = sdr.GetValue(5).ToString();
                 bet.cur_level = "1";

                 //game level condition
                 if (sdr.GetValue(6).ToString() == "1")
                 {
                     if (sdr.GetValue(4).ToString() == "5")
                     {
                         bet.cur_level = "2";
                         if (sdr.GetValue(7).ToString() == "10")
                         {
                             bet.cur_level = "3";

                             if (Session["winhands"].ToString() == "4")
                             {
                                 bet.cur_level = "4";

                                 if (Session["winhands"].ToString() == "6")
                                 {
                                     bet.cur_level = "5";

                                     if ((sdr.GetValue(4).ToString() == "5") && (sdr.GetValue(0).ToString() == "20000"))
                                     {
                                         bet.cur_level = "6";
                                     } //level 6 close

                                 } //level 5 close
                             } //level 4 close
                         } //level 3 close
                     } //level 2 close
                 } //level 1 close
                 conn.Close();


               

             } //action close
             return PartialView(bet);
         }


         /* Show Scores*/ 
        public ActionResult Score()
         {
             var conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["ptpcon"].ConnectionString);
             conn.Open();
             gwSvc.gwsSoapClient gws2 = new gwSvc.gwsSoapClient();
             PtpBettingDetial bet2 = new PtpBettingDetial();
             gwSvc.gpReviewBet rb = new gwSvc.gpReviewBet();
             gwSvc.gpHeader transSec2 = new gwSvc.gpHeader();
             gwSvc.gpAvailablePrograms ap = new gwSvc.gpAvailablePrograms();

             transSec2.userName = "ptpapp1";
             transSec2.passWord = "Ptp!Usr1";
             transSec2.cmty = "PTP";

             ap = gws2.AMTrequestAvailablePrograms(transSec2);

             int cr = (int)Session["runingpname"];
             if (cr != ap.programList[0].currentRace)
             {
                 ArrayList placedbetnew = new ArrayList();
                 Session["placedbet"] = placedbetnew;
                 Session["runingpname"] = ap.programList[0].currentRace;
             }

             ArrayList serialno = (ArrayList)Session["placedbet"];
             ArrayList bettype = new ArrayList();

             bet2.total = 0;
             bet2.serialnumbers = new ArrayList();
             bet2.hand_chosen = new ArrayList();
             bet2.amount_placed = new ArrayList();
             bet2.amount_won = new ArrayList();
             bet2.betstatus = new ArrayList();
             bet2.bet_type = bettype;

             foreach (String serial in serialno)
             {
                 rb = gws2.AMTreviewBet(transSec2, serial);


                 if (rb.errorCode == 0)
                 {

                     String[] betdet = rb.betDetails.Split(' ');

                     bet2.bet_type.Add(betdet[3]);
                     bet2.amount_won.Add(rb.winningAmount);
                     bet2.amount_placed.Add(rb.betCost);
                     bet2.hand_chosen.Add(betdet[4]);
                     bet2.betstatus.Add(rb.betStatus);
                     if (rb.betStatus == "W")
                     {
                         int winhand =  Convert.ToInt32(Session["winhands"]);

                         winhand++;
                         Session["winhands"] = winhand;

                         string queryString = "SELECT Total_chip_count,no_of_wins,MAX(highest_chip_win) FROM dbo.PTP_Facebook_Player where Facebook_id =" + Session["fbid"];
                         int chip_bal = 0;
                         int nw = 0;
                         int won_amount = 0;
                         SqlCommand command = new SqlCommand(queryString, conn);

                         SqlDataReader sdr = command.ExecuteReader();

                         int hc = 0;
                         if (sdr.Read())
                         {
                             chip_bal = Convert.ToInt32(sdr.GetValue(0));
                             nw = Convert.ToInt32(sdr.GetValue(1));
                             won_amount = Convert.ToInt32(rb.winningAmount);

                             chip_bal = chip_bal + won_amount;
                             nw++;

                             //update highest chip
                             if (Convert.ToInt32(sdr.GetValue(2)) < Convert.ToInt32(rb.winningAmount))
                             {
                                 hc = Convert.ToInt32(rb.winningAmount);
                             }
                             else
                             {
                                 hc = Convert.ToInt32(sdr.GetValue(2));
                             }
                             sdr.Close();


                             queryString = "UPDATE dbo.PTP_Facebook_Player SET [Total_chip_count]=@chipbal,[no_of_wins]=@nw,[highest_chip_win]=@won_amount WHERE Facebook_id =" + Session["fbid"];
                             SqlCommand command2 = new SqlCommand(queryString, conn);
                             command2.Parameters.Add("@chipbal", SqlDbType.Decimal).Value = System.Convert.ToDecimal(Convert.ToString(chip_bal));
                             command2.Parameters.Add("@nw", SqlDbType.Decimal).Value = nw;
                             command2.Parameters.Add("@won_amount", SqlDbType.Decimal).Value = hc;

SampleFacebookApp/Views/Shared/Chip_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#">
  <meta charset="utf-8" />
    <meta property="og:type" content="og:product" />

    <meta property="og:title" content="Friend Smash Coin!" />
  <meta property="og:plural_title" content="Friend Smash Coins!" />
  <meta property="og:image" content="http://192.168.2.19/ptpgame/Images/coin64.png" />
  <meta property="og:url" content="http://192.168.2.19/ptpgame/coin.html" />
  <meta property="og:description" content="Get some coins and buy more lives and bombs!" />
  <meta property="product:price:amount" content="0.10"/>
  <meta property="product:price:currency" content="USD"/>
  <meta property="product:price:amount" content="0.12"/>
  <meta property="product:price:currency" content="CAD"/>
  <meta property="product:price:amount" content="0.08"/>
  <meta property="product:price:currency" content="EUR"/>
  <meta property="product:price:amount" content="0.06"/>
  <meta property="product:price:currency" content="GBP"/>
  <meta property="product:price:amount" content="1.2"/>
  <meta property="product:price:currency" content="MXN"/>
  <meta property="product:price:amount" content="0.50"/>
  <meta property="product:price:currency" content="BRL"/>
  <meta property="product:price:amount" content="0.64"/>
  <meta property="product:price:currency" content="SEK"/>
</head>
<body> 
    
        @RenderBody()   
	
	
</body>
</html>

SampleFacebookApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Mvc.Facebook
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>@ViewBag.Title - Post Time Poker</title>
    @Styles.Render("~/Content/cssone")
     @Scripts.Render("~/bundles/jquery")
     @Scripts.Render("~/bundles/jsfirst")
 
    
    

    <script type="text/javascript">
     $(document).ready(function () {

         /*fb share*/

         $("#fb_share").click(function () {
               FB.ui(
                       {
                        method: 'share',
                        href: 'https://apps.facebook.com/posttimepoker',
                        name: 'I have won free chips',
                        caption: 'Play Post Time Poker',
                        },
                        function (response) {
                        if (response && !response.error_code) {
                         //alert('Posting completed.');
                     } else {
                      // alert('Error while posting.');
     }
 }
);
        //     alert("hiiii");
         });

		$("#chip_balance #close").click(function () {
			$("#chip_balance").hide();	
			$("#backgroundPopup").hide('slow');			
		});
		$("#invite_frnd #close").click(function () {
			//$("#invite_frnd").hide();	
			$('#invite_frnd').stop().animate({'top':-200}, 500);									
			$("#backgroundPopup").hide();			
			$("#gif1").attr("src", '');
			$("#gif2").attr("src", '');
			$("#gif3").attr("src", '');
			$("#gif4").attr("src", '');
		});
         $('.win_chips #close').click(function () {
             var value = $('#congratulations p span').html();
             $.ajax({
                 type: "POST",
                 url: '@Url.Action("Addchip","WagerBoard")',
                 content: "application/json; charset=utf-8",
                 data: ({chip:value}),
	                   success: function (data) {
					
					$('#chip_balance p').html('Your Chip Balance is Now <span>' + data + '</span>');
					$("#chip_balance").show(1000);
					setInterval(function() {					 					
						$('#chip_balance').stop().animate({'top':200}, 1000);					
					}, 1000);
	                      // alert('Your Chip Balance is Now '+data);
	                     //  alert($('#congratulations p span').html());
	              },
             });
		 				
		});
	 });
     $(document).ready(function () {
         $('#liquid1').liquidcarousel({ height: 129, duration: 100, hidearrows: false });
		$('#gameboard').bind('contextmenu', function(e) {
				return false;
			}); 	

     });
	 
</script>
    <script type="text/javascript">//<![CDATA[ 
        $(window).load(function () { });
        $(window).bind("load", function () {
            $('#dvLoading').fadeOut(2000);
        });
	</script>
  
 
    

<style type="text/css">
        .auto-style1 {
            width: 800px;
            height: 1100px;
        }
    </style>

</head>
<body>
   



  <script>
      window.fbAsyncInit = function () {
          FB.init({
              appId: '@GlobalFacebookConfiguration.Configuration.AppId', // App ID
          status: true, // check login status
          cookie: true, // enable cookies to allow the server to access the session
          xfbml: true  // parse XFBML
      });
    };

  // Load the SDK Asynchronously
  (function (d) {
      var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
      if (d.getElementById(id)) { return; }
      js = d.createElement('script'); js.id = id; js.async = true;
      js.src = "//connect.facebook.net/en_US/all.js";
      ref.parentNode.insertBefore(js, ref);
  }(document));
  </script>
    
  <script>

           function callback(response) {
          console.log(response);
          if (response.request) {

              $.ajax({
                  type: "POST",
                  url: '@Url.Action("Addchip","WagerBoard")',
                 content: "application/json; charset=utf-8",
                 data: ({ chip: "50"}),
                 success: function (data) {
					$('#invite_frnd p').html('Your Chip Balance is Now <span>' + data + '</span>');					
					$("#backgroundPopup").show();
					$('#invite_frnd').stop().animate({'top':800}, 1000);
					setTimeout(function() {
						$("#gif1").attr("src", 'Images/gif/Fireworks-01-june.gif');
						$('#gif1').show();
					}, 2000);					
					setTimeout(function() {
						$('#gif1').hide();
						$("#gif2").attr("src", 'Images/gif/graphics-fireworks-032090.gif');
						$('#gif2').show();
					}, 3200);					
					setTimeout(function() {
						$('#gif2').hide();
						$("#gif3").attr("src", 'Images/gif/Fireworks-02-june.gif');
						$('#gif3').show();
					}, 4500);					
					setTimeout(function() {
						$('#gif3').hide();
						$("#gif4").attr("src", 'Images/gif/graphics-fireworks-158568.gif');
						$('#gif4').show();
					}, 5700);
					setTimeout(function() {						
						$('#gif4').hide();
					}, 6500);					
					
                     //alert('Your Chip Balance is Now ' + data);
                     //  alert($('#congratulations p span').html());
                 },
              });

           
          }
      }
      function Invite(frndid)
      {

          FB.ui({method: 'apprequests',
              message: 'join me to play Post Time Poker for unlimited excitement!',
              to: frndid
          }, callback);

          
    /*      var gCoinsObjectURL = 'http://apps.facebook.com/ptpfacebook/coin.html';


          console.log("Constructing Request ID: " + frndid);
          FB.ui({
              method: 'pay',
              action: 'purchaseitem',
              product: "https://graph.facebook.com/292914537550412",
              request_id: frndid,
              quantity: 3
          },
    verifyPayment
    );
       */
      }

    /*  function verifyPayment(data) {
          if (!data) {
              alert("There was an error processing your payment. Please try again!");
              return;
          }

          console.log("Payment verification complete");
          console.log(data);

          if (data.error_code) {
              if (data.error_code != 1383010) {
                  alert("There was an error processing your payment." + data.error_message + " Error code:" + data.error_code);
              }
              return;
          }

          closeStore();
          gPlayerCoins = parseInt(gPlayerCoins) + parseInt(data.quantity);

          var success = showPopUp({ img: 'coin_bundle64.png', title: 'Coins!' });
          success.innerHTML = "You bought " + data.quantity + " coins!<br>Let's smash some friends!";

          $('.player_coins').html(gPlayerCoins);
      }
      */
  </script>  

    @RenderBody()  	

   
</body>
</html>